[package]
name = "webscale"
version = "0.9.4"
authors = ["Lauri MÃ¤kinen <lauri.sakari.makinen@gmail.com>", "David Kushner <root@davidkushner.me>"]

[dependencies]
toml = "0.2"
log = "0.3.6"
glob = "*"
serde = "0.8.4"
semver = "0.4.0"
webscale_plugin = { path = "../webscale_plugin" }

