[package]
name = "webscale"
version = "0.1.0"
authors = ["Lauri MÃ¤kinen <lauri.sakari.makinen@gmail.com>"]

[dependencies]
irc = "0.11.3"
hyper = "0.9.9"
config = "~0.1.0"
regex = "0.1.47"
rquery = "0.2.1"
