[package]
name = "webscale"
version = "0.9.4"
authors = ["Lauri MÃ¤kinen <lauri.sakari.makinen@gmail.com>"]
exclude = [
  "**/*.json",
  "**/*.txt"
]

[dependencies]
irc = "0.11.3"
hyper = "0.9.9"
regex = "0.1.47"
getopts = "0.2"
