[package]
name = "webscale"
version = "0.9.4"
authors = ["Lauri MÃ¤kinen <lauri.sakari.makinen@gmail.com>", "David Kushner <root@davidkushner.me>"]

[dependencies]
toml = "0.2"
rustc-serialize = "0.3"
log = "0.3.6"
glob = "*"
semver = "0.4.0"

